name: Node.js Package

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - run: git config --global user.email "varunsridharan23+npmbot@gmail.com" && git config --global user.name "NPM BOT"
      - run: npm install
      - run: gulp compile
      - run: npm version patch
